# How many seconds must a player wait between starting raids
# You can also use "antiraidfarm.bypass" perm to bypass this prevention
# By Default raid will put to 180 seconds = 3 minutes
raid-cooldown-seconds: 180