name: AntiRaidFarm
version: '${project.version}'
main: me.thunthean.AntiRaidFarm
api-version: '1.17'
commands:
  antiraidfarm:
    aliases:
      - anf
    description: A antiraidfarm main command
  raidremain:
    aliases:
      - rem
      - raid-remain
  description: A antiraidfarm command that check for your raid remaining